### ISSUE TITLE
Unable to Login the server.

### ISSUE THREAD

**Issue by BlueSilverXIII** [AjaxVM/peaceful-carnage-modpack#57]
As soon as i put on Botania's Band of Mana, the server kicked me out. its not a full crash so there's no client crash log. now i cant login and gives me "internal server error" everytime i try to login.

**Comment by AjaxVM** [comment]
Console reports:

[20:34:52] [INFO] BlueSilverXIII joined the game

[20:34:52] [ERROR] Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@79da9356:

[20:34:52] java.lang.NoSuchMethodError: baubles.common.network.PacketSync.<init>(Lnet/minecraft/entity/player/EntityPlayer;I)V

[20:34:52] at vazkii.botania.common.core.handler.InternalMethodHandler.sendBaubleUpdatePacket(InternalMethodHandler.java:263) ~[InternalMethodHandler.class:?]

[20:34:52] at vazkii.botania.api.mana.ManaItemHandler.dispatchManaExact(ManaItemHandler.java:284) ~[ManaItemHandler.class:?]

[20:34:52] at vazkii.botania.common.item.equipment.bauble.ItemAuraRing.onWornTick(ItemAuraRing.java:35) ~[ItemAuraRing.class:?]

[20:34:52] at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:96) ~[EventHandlerEntity.class:?]

[20:34:52] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_EventHandlerEntity_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]

[20:34:52] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]

[20:34:52] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]

[20:34:52] at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368) [FMLCommonHandler.class:?]

[20:34:52] at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]

[20:34:52] at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]

[20:34:52] at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]

[20:34:52] at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]

[20:34:52] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]

[20:34:52] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]

[20:34:52] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]

[20:34:52] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]

[20:34:52] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]

[20:34:52] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]

[20:34:52] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]

[20:34:52] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

[20:34:52] [ERROR] Index: 2 Listeners:

[20:34:52] [ERROR] 0: NORMAL

[20:34:52] [ERROR] 1: ASM: class twilightforest.TFTickHandler playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 2: ASM: baubles.common.event.EventHandlerEntity@3734fc77 playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 3: ASM: tamaized.tammodized.registry.PortalHandlerRegistry@3cd5967b update(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 4: ASM: net.blay09.mods.netherportalfix.NetherPortalFix@24e891c0 onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 5: ASM: tamaized.voidcraft.common.events.VoidTickEvent@48a8bd54 onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 6: ASM: tamaized.voidcraft.common.events.CapabilitySyncEvent@47f979b5 onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 7: ASM: levelup2.skills.crafting.FoodGrowthBonus@eb151bd onPlayerUpdate(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 8: ASM: levelup2.skills.mining.SprintSpeedBonus@585e0a35 onPlayerSprint(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 9: ASM: levelup2.skills.combat.StealthSpeed@eaf9432 onPlayerSneak(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V

[20:34:52] [ERROR] 10: ASM: Block{null} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V

[20:34:52] [WARN] Failed to handle packet for /76.104.221.17:60131

[20:34:52] net.minecraft.util.ReportedException: Ticking player

[20:34:52] at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]

[20:34:52] at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]

[20:34:52] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]

[20:34:52] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]

[20:34:52] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]

[20:34:52] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]

[20:34:52] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]

[20:34:52] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]

[20:34:52] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]

[20:34:52] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

[20:34:52] Caused by: java.lang.NoSuchMethodError: baubles.common.network.PacketSync.<init>(Lnet/minecraft/entity/player/EntityPlayer;I)V

[20:34:52] at vazkii.botania.common.core.handler.InternalMethodHandler.sendBaubleUpdatePacket(InternalMethodHandler.java:263) ~[InternalMethodHandler.class:?]

[20:34:52] at vazkii.botania.api.mana.ManaItemHandler.dispatchManaExact(ManaItemHandler.java:284) ~[ManaItemHandler.class:?]

[20:34:52] at vazkii.botania.common.item.equipment.bauble.ItemAuraRing.onWornTick(ItemAuraRing.java:35) ~[ItemAuraRing.class:?]

[20:34:52] at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:96) ~[EventHandlerEntity.class:?]

[20:34:52] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_EventHandlerEntity_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]

[20:34:52] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]

[20:34:52] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]

[20:34:52] at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:368) ~[FMLCommonHandler.class:?]

[20:34:52] at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]

[20:34:52] at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]

[20:34:52] at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]

[20:34:52] ... 9 more


I wonder if there is an issue with botania/baubles in multiplayer? :(

**Comment by AjaxVM** [comment]
https://github.com/AllTheMods/ATM-3/issues/377

**Comment by AjaxVM** [comment]
https://github.com/Vazkii/Botania/issues/2517

**Comment by AjaxVM** [comment]
Huh - didn't realize this referenced all the way into the other repos... O.o
Note to all: be careful what you link :D
